### ISSUE TITLE
news_list 이슈

### ISSUE THREAD

**Issue by MinCheol-Yoon** [20-2-SKKU-OSS/2020-2-OSS-7#12]
다른 뉴스 기사의 경우 bs4의 select('div.news_list') 함수를 통해 여러 뉴스 리스트를 모아 날짜별로 크롤링을 할 수 있지만
스포츠 기사의 경우 js코드를 통해 api호출 형식으로 뉴스리스트를 불러와서 bs4 htmpl.parser로 코드를 가져올 경우 뉴스리스트를 가져오지 못하네요. 
js의 원본 코드도 가져오려 했으나 서버쪽에 접근하지 않는이상 힘드네요..
네이버 검색탭을 이용해서 크롤링하는 방식으로 하는건 어떨까요

**Comment by uitae** [comment]
12/1일 회의합시다
