### ISSUE TITLE
과제 목표를 바꾸는 것이 어떨까요

### ISSUE THREAD

**Issue by MinCheol-Yoon** [20-2-SKKU-OSS/2020-2-OSS-7#13]
기존에는 오픈소스 코드는 카테고리 별로 크롤링을 했습니다. 
단점은 스포츠 기사를 크롤링 하지 못한다는 것입니다.
이전 issue에서 적었든 스포츠 기사'만' 크롤링 하는 것이 지금은 매우 힘들어보입니다.
그래서 언론사 별로 크롤링 하는 코드를 작성하는 것으로 목표를 바꾸면 좋을 것 같습니다. 

뉴스 기사를 들어가 보면 https://sports.news.naver.com/news.nhn?oid=382&aid=0000874864 와 같은 url형식으로 이루어져있습니다.

여기서 oid는 언론사 별 고유 id입니다.
위와 같은 경우 382는 스포츠 동아를 뜻하는 것입니다.

이 oid를 이용하여 언론사별 크롤링을 하면 좋을 것 같습니다.

**Comment by uitae** [comment]
처음 개선사항에서도 언급했었듯이, 스포츠기사 크롤링하는 것을 주된 목표가 아닌 부가적인 기능들을 개발하는 것을 주된 목표로 하기로 했었습니다. 

언론사별 크롤링 기능
카테고리별 크롤링 기능
을 먼저 개발하는 것이 좋아보입니다.
