### ISSUE TITLE
언론사별 크롤링관련 issue

### ISSUE THREAD

**Issue by dayeong089** [20-2-SKKU-OSS/2020-2-OSS-7#26]
get_oid 함수를 추가해서 언론사별 크롤링이 가능하게 코드를 수정하였는데
몇몇 언론사의 경우에 index error가 발생하는데 원인을 잘 모르겠습니다.

**Comment by JihyeJung-Work** [comment]
그  언론사에 크롤링할 기사가 없는건 아닌가요? index에러가 뜨는거 보면

**Comment by dayeong089** [comment]
네네 그런거같은데 그럼 그런 언론사들을 목록에서 삭제할까요?

**Comment by JihyeJung-Work** [comment]
크롤링할 분야마다 기사가 있는지 없는지는 다르지 않을까요?

**Comment by dayeong089** [comment]
음 그럼 에러가 안뜨고 크롤링할 기사가 없다는 식의 메세지가 작성되도록 코드를 수정해야할것같네용....

**Comment by JihyeJung-Work** [comment]
입력한 크롤링할 개수(aid)가 크롤링할 기사 개수보다 적으면 예외처리될수 있도록 해야할 것 같습니다.

**Comment by dayeong089** [comment]
몇몇 뉴스가 aid 시작 번호가 달라서 발생한 문제로, 그 경우에 일괄적으로 aid='1000'으로 지정하고 해결하였습니다
